# Site settings
name: Sonquain的小窝
email: 1138699365@qq.com
author: etk3mfalive
url: http://www.sonquain.com
resume_site: http://www.sonquain.com/Resume.io/
github: https://github.com/etk3mfalive/
baseurl: ""
description: a stunning boy
meta_description: Natori;Sonnet;37;世界本就是个草台班子;
motto: Where there is no vision, there is no hope.
banner: Each moment,now night.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
